version: '2.1'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    network_mode: bridge
    command: --wait_timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: penis123
      MYSQL_DATABASE: pajbot
    volumes:
     - pajbot-mariadb:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=penis123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    network_mode: bridge
    volumes:
      - pajbot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  traefik:
    image: traefik
    restart: always
    container_name: traefik
    network_mode: bridge
    command: --api --docker --docker.exposedbydefault=false --ping
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/traefik" ,"healthcheck", "--ping"]
      interval: 30s
      timeout: 3s
      retries: 30

  pajbot:
    image: leppunen/pajbot:test
    restart: always
    container_name: pajbot-${STREAMERNAME:?STREAMERNAME}
    network_mode: bridge
    depends_on:
       redis:
         condition: service_healthy
       mariadb:
         condition: service_healthy
       traefik:
         condition: service_healthy
    volumes:
      - '/opt/pajbot/:/app/configs'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.web.frontend.rule=Host:${DOMAIN:?DOMAIN}"
      - "traefik.web.port=8855"
      - "traefik.ws.frontend.rule=Host:${DOMAIN:?DOMAIN};Path:/ws"
      - "traefik.ws.port=5555"
    environment:
      CONFIG: ${CONFIG:?CONFIG}

volumes:
  pajbot-redis:
    driver: local
    name: pajbot-redis
  pajbot-mariadb:
    driver: local
    name: pajbot-mariadb
